language: rust
notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  allow_failures:
  - name: nightly-channel
  fast_finish: true
  include:
  - name: stable-channel
    rust: stable
  - name: beta-channel
    rust: beta
  - name: nightly-channel
    rust: nightly

  - name: clippy-lint
    rust: stable
    before_script:
    - rustup component add clippy
    script:
    - cargo clippy --all-targets --all-features -- -D warnings
  - name: style-check
    rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check

cache:
  directories:
  - /home/travis/.cargo

before_script:
- rm -rf /home/travis/.cargo/registry
script:
- cargo build --verbose --all
- cargo test --verbose --all
