[package]
name = "cang-jie"
version = "0.3.0"
authors = ["DCjanus <DCjanus@dcjanus.com>"]
edition = "2018"
description = "A Chinese tokenizer for tantivy"
license = "MIT"
repository = "https://github.com/DCjanus/cang-jie"
readme = "README.MD"
keywords = ["search", "tokenizer", "Chinese", "tantivy"]

[dependencies]
tantivy = "0.9"
jieba-rs = "0.2"
log = "0.4"

[dev-dependencies]
chrono = "0.4"
flexi_logger = "0.11"
