[package]
name = "cang-jie"
version = "0.7.0"
authors = ["DCjanus <DCjanus@dcjanus.com>"]
edition = "2018"
description = "A Chinese tokenizer for tantivy"
license = "MIT"
repository = "https://github.com/DCjanus/cang-jie"
readme = "README.MD"
keywords = ["search", "tokenizer", "Chinese", "tantivy"]

[dependencies]
tantivy = "0.12.0"
jieba-rs = { version = "0.4.10", default-features = false }
log = "0.4.8"

[dev-dependencies]
flexi_logger = "0.14.8"
